DROP TABLE IF EXISTS book;
CREATE TABLE book(
	isbn	BIGINT PRIMARY KEY,
	book_title VARCHAR(500) NOT NULL, 
	category VARCHAR(100) NOT NULL,
	rental_price NUMERIC(10,2) NOT NULL CHECK (rental_price >= 0),
	author VARCHAR(500) NOT NULL,
	publisher VARCHAR(500) NOT NULL,
	total_copies INT NOT NULL CHECK (total_copies >= 0),
	available_copies INT NOT NULL CHECK ((available_copies >= 0) AND (available_copies <= total_copies))
);

DROP TABLE IF EXISTS branch;
CREATE TABLE branch(
	branch_id INT PRIMARY KEY,
	manager_id INT UNIQUE,		--fk
	branch_address TEXT NOT NULL,
	contact_no VARCHAR(20) NOT NULL CHECK(contact_no ~ '^[0-9+ -]{10,20}$')
);

DROP TABLE IF EXISTS employee;
CREATE TABLE employee(
	emp_id INT PRIMARY KEY,
	emp_name VARCHAR(100) NOT NULL,
	position VARCHAR(100) NOT NULL CHECK(position IN ('Clerk', 'Manager', 'Assistant', 'Librarian')),
	branch_id INT NOT NULL  			--fk
);

DROP TABLE IF EXISTS issue_return;
CREATE TABLE issue_return(
	issued_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	member_id INT NOT NULL,  --fk
	emp_id INT NOT NULL,  --fk
	isbn BIGINT NOT NULL, --fk
	issued_date DATE NOT NULL,
	due_date DATE NOT NULL CHECK(due_date > issued_date),
	return_date DATE CHECK(return_date IS NULL OR return_date >= issued_date)
);

DROP TABLE IF EXISTS member;
CREATE TABLE member(
	member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	member_name VARCHAR(100) NOT NULL,
	member_address TEXT NOT NULL,
	reg_date DATE NOT NULL CHECK(reg_date <= CURRENT_DATE)
);

ALTER TABLE branch
ADD CONSTRAINT fk_employee
FOREIGN KEY (manager_id)
REFERENCES employee(emp_id);

ALTER TABLE employee
ADD CONSTRAINT fk_branch
FOREIGN KEY (branch_id)
REFERENCES branch(branch_id);

ALTER TABLE issue_return
ADD CONSTRAINT fk_member
FOREIGN KEY (member_id)
REFERENCES member(member_id);

ALTER TABLE issue_return
ADD CONSTRAINT fk_employee
FOREIGN KEY (emp_id)
REFERENCES employee(emp_id);

ALTER TABLE issue_return
ADD CONSTRAINT fk_book
FOREIGN KEY (isbn)
REFERENCES book(isbn);

SELECT last_value
FROM issue_return_issued_id_seq;

SELECT setval(
pg_get_serial_sequence('issue_return', 'issued_id'), (SELECT MAX(issued_id) FROM issue_return)
);

SELECT setval(
pg_get_serial_sequence('member', 'member_id'), (SELECT MAX(member_id) FROM member)
);